### ISSUE TITLE
Different colors for up-to-date vs outdated

### ISSUE THREAD

**Issue by fschutt** [srijs/deps.rs#21]
I used this on my repo here: https://github.com/fschutt/printpdf - the dependencies are up to date, but the color of the badge doesn't really reflect that, it's not green like I'd expect it to be. I would use different colors for up-to-date vs outdated.

**Comment by srijs** [comment]
Hi @fschutt!

Looking at https://deps.rs/repo/github/fschutt/printpdf the badge shows as green to me.

Badges are heavily cached so it might take up to ten minutes for them to refresh after changes have been made to the repo.

Can you confirm whether you are still having this issue?
