### ISSUE TITLE
Support looking at `crates.io` releases

### ISSUE THREAD

**Issue by mathstuf** [srijs/deps.rs#22]
Similar to `docs.rs`, it'd be nice to have a report for packages on `crates.io`.

**Comment by srijs** [comment]
Hi @mathstuf!

Can you provide more details how you'd envisioned this to look?

Are you referring to a page like https://docs.rs/crate/futures?

Cheers!

**Comment by mathstuf** [comment]
Yes. Most of the projects I work on are hosted on a local (public) Gitlab instance; it seems that it wouldn't be supported on the website as-is (gitlab.com support is probably doable, but hosted instances would be harder to manage), but using crates.io would allow for getting these reports.

**Comment by srijs** [comment]
Cool, that makes sense to me!

**Comment by srijs** [comment]
Support for crates just rolled out to production.

An example is here: https://deps.rs/crate/rayon

You can also see a list of popular crates on the [landing page](https://deps.rs/).

**Comment by mathstuf** [comment]
Thanks!
